<?php

namespace AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
	 public function getEventsAjax($eventid)
    {
        $qb =  $this->_em->createQueryBuilder('d')
                 ->select('d')
                    ->from('AdminBundle:Image',  'd')
                    ->leftJoin('d.event', 'event')
                     ->where('event.id = '.$eventid    )
                     ->andwhere ("d.url not like '%empty.png'")
                    ->getQuery()
                    ->getArrayResult();
   
    return $qb;
        
    }
}
