<?php

namespace AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
	public function getBestSeller($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
                   ->select('b')
                   ->where('b.isbestseller =  1 ');
        return $qb->getQuery()->getResult();
    }
    public function getItemByMonth($month)
    {
        $qb = $this->createQueryBuilder('b')
                   ->select('b')
                   ->leftJoin('b.months', 'months')
                   ->where('months.id ='.$month);
        return $qb->getQuery()->getResult();
    }
}
