<?php

namespace AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthRepository extends EntityRepository
{
}
