<?php

namespace AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MonthItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthItemRepository extends EntityRepository
{
	 
}
